name: Bug Report
description: Report a bug.
title: "Bug Report"
body:
  - type: textarea
    id: where
    attributes:
      label: Where did the bug happen?
      description: Was it in a command or a system?
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug.
      description: Be precise and specific.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What was expected to happen?
      description: What was it originally supposed to do?
    validations:
      required: true
